from typing import Literal, List, Dict

entities = Literal[
    "ACTOR",
    "ART_DIRECTOR",
    "BOOK",
    "CHARACTER",
    "COMPOSER",
    "CREATOR",
    "DIRECTOR",
    "FRANCHISE",
    "GENRE",
    "MOVIE",
    "MUSIC",
    "PRODUCER",
    "SHOW",
    "VIDEO_GAME",
    "WRITER",
]

relations = Literal[
    "ADAPTED_FROM",
    "BELONGS_TO_GENRE",
    "COLLABORATED_WITH",
    "COMPOSED",
    "CREATED",
    "DIRECTED",
    "FEATURED_IN",
    "INFLUENCED",
    "INFLUENCED_FROM",
    "PART_OF",
    "PLAGIARIZED",
    "PREQUEL_TO",
    "PRODUCED",
    "REMAKE_OF",
    "SEQUEL_TO",
    "SIMILAR_TO",
    "SPIN_OFF_OF",
    "STARRED_IN",
    "WROTE",
]

schema: Dict[entities, List[relations]] = {
    "ACTOR": ["COLLABORATED_WITH", "INFLUENCED", "STARRED_IN"],
    "ART_DIRECTOR": [
        "BELONGS_TO_GENRE",
        "COLLABORATED_WITH",
        "CREATED",
        "INFLUENCED",
        "INFLUENCED_FROM",
        "PLAGIARIZED",
    ],
    "BOOK": [
        "ADAPTED_FROM",
        "BELONGS_TO_GENRE",
        "INFLUENCED",
        "INFLUENCED_FROM",
        "PART_OF",
        "PLAGIARIZED",
        "PREQUEL_TO",
        "SEQUEL_TO",
        "SIMILAR_TO",
    ],
    "CHARACTER": [
        "FEATURED_IN",
        "INFLUENCED",
        "INFLUENCED_FROM",
        "PART_OF",
        "SIMILAR_TO",
    ],
    "COMPOSER": [
        "COLLABORATED_WITH",
        "COMPOSED",
        "INFLUENCED",
        "INFLUENCED_FROM",
        "PLAGIARIZED",
    ],
    "CREATOR": [
        "COLLABORATED_WITH",
        "CREATED",
        "INFLUENCED",
        "INFLUENCED_FROM",
        "PLAGIARIZED",
    ],
    "DIRECTOR": [
        "COLLABORATED_WITH",
        "DIRECTED",
        "INFLUENCED",
        "INFLUENCED_FROM",
        "PLAGIARIZED",
    ],
    "FRANCHISE": ["INFLUENCED", "INFLUENCED_FROM", "PART_OF", "SIMILAR_TO"],
    "GENRE": ["INFLUENCED", "INFLUENCED_FROM", "SIMILAR_TO"],
    "MOVIE": [
        "ADAPTED_FROM",
        "BELONGS_TO_GENRE",
        "INFLUENCED",
        "INFLUENCED_FROM",
        "PART_OF",
        "PLAGIARIZED",
        "PREQUEL_TO",
        "REMAKE_OF",
        "SEQUEL_TO",
        "SIMILAR_TO",
    ],
    "MUSIC": [
        "BELONGS_TO_GENRE",
        "INFLUENCED",
        "INFLUENCED_FROM",
        "PART_OF",
        "PLAGIARIZED",
        "SIMILAR_TO",
    ],
    "PRODUCER": ["COLLABORATED_WITH", "PRODUCED"],
    "SHOW": [
        "ADAPTED_FROM",
        "BELONGS_TO_GENRE",
        "INFLUENCED",
        "INFLUENCED_FROM",
        "PART_OF",
        "PLAGIARIZED",
        "SIMILAR_TO",
        "SPIN_OFF_OF",
    ],
    "VIDEO_GAME": [
        "ADAPTED_FROM",
        "BELONGS_TO_GENRE",
        "INFLUENCED",
        "INFLUENCED_FROM",
        "PART_OF",
        "PLAGIARIZED",
        "PREQUEL_TO",
        "SEQUEL_TO",
        "SIMILAR_TO",
    ],
    "WRITER": [
        "COLLABORATED_WITH",
        "INFLUENCED",
        "INFLUENCED_FROM",
        "PLAGIARIZED",
        "WROTE",
    ],
}
